[phases.setup]
    nixLibs = ['zlib']

[phases.install]
    cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt && prisma generate"]

[start]
    cmd = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"